/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestIndexRouteImport } from './routes/guest.index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as PayCancelledRouteImport } from './routes/pay.cancelled'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as GuestNewRouteImport } from './routes/guest.new'
import { Route as GuestTokenRouteImport } from './routes/guest.$token'
import { Route as ApproveTokenRouteImport } from './routes/approve.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated.super-admin.index'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated.reseller.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedSuperAdminTenantsRouteImport } from './routes/_authenticated.super-admin.tenants'
import { Route as AuthenticatedSuperAdminAdminClientsRouteImport } from './routes/_authenticated.super-admin.admin-clients'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppPendingSignaturesRouteImport } from './routes/_authenticated.app.pending-signatures'
import { Route as AuthenticatedAppDemoRouteImport } from './routes/_authenticated.app.demo'
import { Route as AuthenticatedAppChatbotRouteImport } from './routes/_authenticated.app.chatbot'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated.app.audit'
import { Route as AuthenticatedAppApprovalsRouteImport } from './routes/_authenticated.app.approvals'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated.app.analytics'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAppPdfTemplatesIndexRouteImport } from './routes/_authenticated.app.pdf-templates.index'
import { Route as AuthenticatedAppDraftsIndexRouteImport } from './routes/_authenticated.app.drafts.index'
import { Route as AuthenticatedAppDocumentsIndexRouteImport } from './routes/_authenticated.app.documents.index'
import { Route as AuthenticatedAdminWorkflowsIndexRouteImport } from './routes/_authenticated.admin.workflows.index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated.admin.templates.index'
import { Route as AuthenticatedAdminBusinessVerticalsIndexRouteImport } from './routes/_authenticated.admin.business-verticals.index'
import { Route as ApiPublicSignRequestTokenRouteImport } from './routes/api/public/sign-request.$token'
import { Route as ApiPublicShareTokenRouteImport } from './routes/api/public/share.$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAppDocumentsWysiwygRouteImport } from './routes/_authenticated.app.documents.wysiwyg'
import { Route as AuthenticatedAppDocumentsNewRouteImport } from './routes/_authenticated.app.documents.new'
import { Route as AuthenticatedAppDocumentsIdRouteImport } from './routes/_authenticated.app.documents.$id'
import { Route as AuthenticatedAdminWorkflowsNewRouteImport } from './routes/_authenticated.admin.workflows.new'
import { Route as AuthenticatedAdminWorkflowsIdRouteImport } from './routes/_authenticated.admin.workflows.$id'
import { Route as AuthenticatedAdminTemplatesNewRouteImport } from './routes/_authenticated.admin.templates.new'
import { Route as AuthenticatedAdminTemplatesIdRouteImport } from './routes/_authenticated.admin.templates.$id'
import { Route as AuthenticatedAppDocumentsIdEditorRouteImport } from './routes/_authenticated.app.documents.$id.editor'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/guest/',
  path: '/guest/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCancelledRoute = PayCancelledRouteImport.update({
  id: '/pay/cancelled',
  path: '/pay/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestNewRoute = GuestNewRouteImport.update({
  id: '/guest/new',
  path: '/guest/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestTokenRoute = GuestTokenRouteImport.update({
  id: '/guest/$token',
  path: '/guest/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/super-admin/',
    path: '/super-admin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/reseller/',
    path: '/reseller/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminTenantsRoute =
  AuthenticatedSuperAdminTenantsRouteImport.update({
    id: '/super-admin/tenants',
    path: '/super-admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminAdminClientsRoute =
  AuthenticatedSuperAdminAdminClientsRouteImport.update({
    id: '/super-admin/admin-clients',
    path: '/super-admin/admin-clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppPendingSignaturesRoute =
  AuthenticatedAppPendingSignaturesRouteImport.update({
    id: '/app/pending-signatures',
    path: '/app/pending-signatures',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDemoRoute = AuthenticatedAppDemoRouteImport.update({
  id: '/app/demo',
  path: '/app/demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppChatbotRoute = AuthenticatedAppChatbotRouteImport.update({
  id: '/app/chatbot',
  path: '/app/chatbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppApprovalsRoute =
  AuthenticatedAppApprovalsRouteImport.update({
    id: '/app/approvals',
    path: '/app/approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/app/analytics',
    path: '/app/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppPdfTemplatesIndexRoute =
  AuthenticatedAppPdfTemplatesIndexRouteImport.update({
    id: '/app/pdf-templates/',
    path: '/app/pdf-templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDraftsIndexRoute =
  AuthenticatedAppDraftsIndexRouteImport.update({
    id: '/app/drafts/',
    path: '/app/drafts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsIndexRoute =
  AuthenticatedAppDocumentsIndexRouteImport.update({
    id: '/app/documents/',
    path: '/app/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsIndexRoute =
  AuthenticatedAdminWorkflowsIndexRouteImport.update({
    id: '/admin/workflows/',
    path: '/admin/workflows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/admin/templates/',
    path: '/admin/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBusinessVerticalsIndexRoute =
  AuthenticatedAdminBusinessVerticalsIndexRouteImport.update({
    id: '/admin/business-verticals/',
    path: '/admin/business-verticals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicSignRequestTokenRoute =
  ApiPublicSignRequestTokenRouteImport.update({
    id: '/api/public/sign-request/$token',
    path: '/api/public/sign-request/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShareTokenRoute = ApiPublicShareTokenRouteImport.update({
  id: '/api/public/share/$token',
  path: '/api/public/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppDocumentsWysiwygRoute =
  AuthenticatedAppDocumentsWysiwygRouteImport.update({
    id: '/app/documents/wysiwyg',
    path: '/app/documents/wysiwyg',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsNewRoute =
  AuthenticatedAppDocumentsNewRouteImport.update({
    id: '/app/documents/new',
    path: '/app/documents/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsIdRoute =
  AuthenticatedAppDocumentsIdRouteImport.update({
    id: '/app/documents/$id',
    path: '/app/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsNewRoute =
  AuthenticatedAdminWorkflowsNewRouteImport.update({
    id: '/admin/workflows/new',
    path: '/admin/workflows/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsIdRoute =
  AuthenticatedAdminWorkflowsIdRouteImport.update({
    id: '/admin/workflows/$id',
    path: '/admin/workflows/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTemplatesNewRoute =
  AuthenticatedAdminTemplatesNewRouteImport.update({
    id: '/admin/templates/new',
    path: '/admin/templates/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTemplatesIdRoute =
  AuthenticatedAdminTemplatesIdRouteImport.update({
    id: '/admin/templates/$id',
    path: '/admin/templates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsIdEditorRoute =
  AuthenticatedAppDocumentsIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedAppDocumentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/guest/$token': typeof GuestTokenRoute
  '/guest/new': typeof GuestNewRoute
  '/p/$token': typeof PTokenRoute
  '/pay/cancelled': typeof PayCancelledRoute
  '/pay/success': typeof PaySuccessRoute
  '/s/$token': typeof STokenRoute
  '/guest/': typeof GuestIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/chatbot': typeof AuthenticatedAppChatbotRoute
  '/app/demo': typeof AuthenticatedAppDemoRoute
  '/app/pending-signatures': typeof AuthenticatedAppPendingSignaturesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/super-admin/admin-clients': typeof AuthenticatedSuperAdminAdminClientsRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRouteWithChildren
  '/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/app/documents/wysiwyg': typeof AuthenticatedAppDocumentsWysiwygRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/api/public/sign-request/$token': typeof ApiPublicSignRequestTokenRoute
  '/admin/business-verticals/': typeof AuthenticatedAdminBusinessVerticalsIndexRoute
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/workflows/': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/drafts/': typeof AuthenticatedAppDraftsIndexRoute
  '/app/pdf-templates/': typeof AuthenticatedAppPdfTemplatesIndexRoute
  '/app/documents/$id/editor': typeof AuthenticatedAppDocumentsIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/guest/$token': typeof GuestTokenRoute
  '/guest/new': typeof GuestNewRoute
  '/p/$token': typeof PTokenRoute
  '/pay/cancelled': typeof PayCancelledRoute
  '/pay/success': typeof PaySuccessRoute
  '/s/$token': typeof STokenRoute
  '/guest': typeof GuestIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/chatbot': typeof AuthenticatedAppChatbotRoute
  '/app/demo': typeof AuthenticatedAppDemoRoute
  '/app/pending-signatures': typeof AuthenticatedAppPendingSignaturesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/super-admin/admin-clients': typeof AuthenticatedSuperAdminAdminClientsRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRouteWithChildren
  '/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/app/documents/wysiwyg': typeof AuthenticatedAppDocumentsWysiwygRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/api/public/sign-request/$token': typeof ApiPublicSignRequestTokenRoute
  '/admin/business-verticals': typeof AuthenticatedAdminBusinessVerticalsIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/app/documents': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/drafts': typeof AuthenticatedAppDraftsIndexRoute
  '/app/pdf-templates': typeof AuthenticatedAppPdfTemplatesIndexRoute
  '/app/documents/$id/editor': typeof AuthenticatedAppDocumentsIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/guest/$token': typeof GuestTokenRoute
  '/guest/new': typeof GuestNewRoute
  '/p/$token': typeof PTokenRoute
  '/pay/cancelled': typeof PayCancelledRoute
  '/pay/success': typeof PaySuccessRoute
  '/s/$token': typeof STokenRoute
  '/guest/': typeof GuestIndexRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/chatbot': typeof AuthenticatedAppChatbotRoute
  '/_authenticated/app/demo': typeof AuthenticatedAppDemoRoute
  '/_authenticated/app/pending-signatures': typeof AuthenticatedAppPendingSignaturesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/super-admin/admin-clients': typeof AuthenticatedSuperAdminAdminClientsRoute
  '/_authenticated/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdRoute
  '/_authenticated/admin/templates/new': typeof AuthenticatedAdminTemplatesNewRoute
  '/_authenticated/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/_authenticated/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/_authenticated/app/documents/$id': typeof AuthenticatedAppDocumentsIdRouteWithChildren
  '/_authenticated/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/_authenticated/app/documents/wysiwyg': typeof AuthenticatedAppDocumentsWysiwygRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
  '/api/public/sign-request/$token': typeof ApiPublicSignRequestTokenRoute
  '/_authenticated/admin/business-verticals/': typeof AuthenticatedAdminBusinessVerticalsIndexRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/workflows/': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/_authenticated/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/_authenticated/app/drafts/': typeof AuthenticatedAppDraftsIndexRoute
  '/_authenticated/app/pdf-templates/': typeof AuthenticatedAppPdfTemplatesIndexRoute
  '/_authenticated/app/documents/$id/editor': typeof AuthenticatedAppDocumentsIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/approve/$token'
    | '/guest/$token'
    | '/guest/new'
    | '/p/$token'
    | '/pay/cancelled'
    | '/pay/success'
    | '/s/$token'
    | '/guest/'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/audit'
    | '/app/chatbot'
    | '/app/demo'
    | '/app/pending-signatures'
    | '/app/profile'
    | '/super-admin/admin-clients'
    | '/super-admin/tenants'
    | '/admin/'
    | '/app/'
    | '/reseller/'
    | '/super-admin/'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/app/documents/$id'
    | '/app/documents/new'
    | '/app/documents/wysiwyg'
    | '/api/public/payments/webhook'
    | '/api/public/share/$token'
    | '/api/public/sign-request/$token'
    | '/admin/business-verticals/'
    | '/admin/templates/'
    | '/admin/workflows/'
    | '/app/documents/'
    | '/app/drafts/'
    | '/app/pdf-templates/'
    | '/app/documents/$id/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/approve/$token'
    | '/guest/$token'
    | '/guest/new'
    | '/p/$token'
    | '/pay/cancelled'
    | '/pay/success'
    | '/s/$token'
    | '/guest'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/audit'
    | '/app/chatbot'
    | '/app/demo'
    | '/app/pending-signatures'
    | '/app/profile'
    | '/super-admin/admin-clients'
    | '/super-admin/tenants'
    | '/admin'
    | '/app'
    | '/reseller'
    | '/super-admin'
    | '/admin/templates/$id'
    | '/admin/templates/new'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/app/documents/$id'
    | '/app/documents/new'
    | '/app/documents/wysiwyg'
    | '/api/public/payments/webhook'
    | '/api/public/share/$token'
    | '/api/public/sign-request/$token'
    | '/admin/business-verticals'
    | '/admin/templates'
    | '/admin/workflows'
    | '/app/documents'
    | '/app/drafts'
    | '/app/pdf-templates'
    | '/app/documents/$id/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/approve/$token'
    | '/guest/$token'
    | '/guest/new'
    | '/p/$token'
    | '/pay/cancelled'
    | '/pay/success'
    | '/s/$token'
    | '/guest/'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/approvals'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/chatbot'
    | '/_authenticated/app/demo'
    | '/_authenticated/app/pending-signatures'
    | '/_authenticated/app/profile'
    | '/_authenticated/super-admin/admin-clients'
    | '/_authenticated/super-admin/tenants'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/reseller/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/admin/templates/$id'
    | '/_authenticated/admin/templates/new'
    | '/_authenticated/admin/workflows/$id'
    | '/_authenticated/admin/workflows/new'
    | '/_authenticated/app/documents/$id'
    | '/_authenticated/app/documents/new'
    | '/_authenticated/app/documents/wysiwyg'
    | '/api/public/payments/webhook'
    | '/api/public/share/$token'
    | '/api/public/sign-request/$token'
    | '/_authenticated/admin/business-verticals/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/workflows/'
    | '/_authenticated/app/documents/'
    | '/_authenticated/app/drafts/'
    | '/_authenticated/app/pdf-templates/'
    | '/_authenticated/app/documents/$id/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  GuestTokenRoute: typeof GuestTokenRoute
  GuestNewRoute: typeof GuestNewRoute
  PTokenRoute: typeof PTokenRoute
  PayCancelledRoute: typeof PayCancelledRoute
  PaySuccessRoute: typeof PaySuccessRoute
  STokenRoute: typeof STokenRoute
  GuestIndexRoute: typeof GuestIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicShareTokenRoute: typeof ApiPublicShareTokenRoute
  ApiPublicSignRequestTokenRoute: typeof ApiPublicSignRequestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/': {
      id: '/guest/'
      path: '/guest'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/cancelled': {
      id: '/pay/cancelled'
      path: '/pay/cancelled'
      fullPath: '/pay/cancelled'
      preLoaderRoute: typeof PayCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/new': {
      id: '/guest/new'
      path: '/guest/new'
      fullPath: '/guest/new'
      preLoaderRoute: typeof GuestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/$token': {
      id: '/guest/$token'
      path: '/guest/$token'
      fullPath: '/guest/$token'
      preLoaderRoute: typeof GuestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/reseller'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/tenants': {
      id: '/_authenticated/super-admin/tenants'
      path: '/super-admin/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof AuthenticatedSuperAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/admin-clients': {
      id: '/_authenticated/super-admin/admin-clients'
      path: '/super-admin/admin-clients'
      fullPath: '/super-admin/admin-clients'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/pending-signatures': {
      id: '/_authenticated/app/pending-signatures'
      path: '/app/pending-signatures'
      fullPath: '/app/pending-signatures'
      preLoaderRoute: typeof AuthenticatedAppPendingSignaturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/demo': {
      id: '/_authenticated/app/demo'
      path: '/app/demo'
      fullPath: '/app/demo'
      preLoaderRoute: typeof AuthenticatedAppDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/chatbot': {
      id: '/_authenticated/app/chatbot'
      path: '/app/chatbot'
      fullPath: '/app/chatbot'
      preLoaderRoute: typeof AuthenticatedAppChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/approvals': {
      id: '/_authenticated/app/approvals'
      path: '/app/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AuthenticatedAppApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/pdf-templates/': {
      id: '/_authenticated/app/pdf-templates/'
      path: '/app/pdf-templates'
      fullPath: '/app/pdf-templates/'
      preLoaderRoute: typeof AuthenticatedAppPdfTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/drafts/': {
      id: '/_authenticated/app/drafts/'
      path: '/app/drafts'
      fullPath: '/app/drafts/'
      preLoaderRoute: typeof AuthenticatedAppDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/': {
      id: '/_authenticated/app/documents/'
      path: '/app/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/': {
      id: '/_authenticated/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows/'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/admin/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/business-verticals/': {
      id: '/_authenticated/admin/business-verticals/'
      path: '/admin/business-verticals'
      fullPath: '/admin/business-verticals/'
      preLoaderRoute: typeof AuthenticatedAdminBusinessVerticalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sign-request/$token': {
      id: '/api/public/sign-request/$token'
      path: '/api/public/sign-request/$token'
      fullPath: '/api/public/sign-request/$token'
      preLoaderRoute: typeof ApiPublicSignRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share/$token': {
      id: '/api/public/share/$token'
      path: '/api/public/share/$token'
      fullPath: '/api/public/share/$token'
      preLoaderRoute: typeof ApiPublicShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/documents/wysiwyg': {
      id: '/_authenticated/app/documents/wysiwyg'
      path: '/app/documents/wysiwyg'
      fullPath: '/app/documents/wysiwyg'
      preLoaderRoute: typeof AuthenticatedAppDocumentsWysiwygRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/new': {
      id: '/_authenticated/app/documents/new'
      path: '/app/documents/new'
      fullPath: '/app/documents/new'
      preLoaderRoute: typeof AuthenticatedAppDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/$id': {
      id: '/_authenticated/app/documents/$id'
      path: '/app/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/new': {
      id: '/_authenticated/admin/workflows/new'
      path: '/admin/workflows/new'
      fullPath: '/admin/workflows/new'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/$id': {
      id: '/_authenticated/admin/workflows/$id'
      path: '/admin/workflows/$id'
      fullPath: '/admin/workflows/$id'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates/new': {
      id: '/_authenticated/admin/templates/new'
      path: '/admin/templates/new'
      fullPath: '/admin/templates/new'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates/$id': {
      id: '/_authenticated/admin/templates/$id'
      path: '/admin/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/$id/editor': {
      id: '/_authenticated/app/documents/$id/editor'
      path: '/editor'
      fullPath: '/app/documents/$id/editor'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIdEditorRouteImport
      parentRoute: typeof AuthenticatedAppDocumentsIdRoute
    }
  }
}

interface AuthenticatedAppDocumentsIdRouteChildren {
  AuthenticatedAppDocumentsIdEditorRoute: typeof AuthenticatedAppDocumentsIdEditorRoute
}

const AuthenticatedAppDocumentsIdRouteChildren: AuthenticatedAppDocumentsIdRouteChildren =
  {
    AuthenticatedAppDocumentsIdEditorRoute:
      AuthenticatedAppDocumentsIdEditorRoute,
  }

const AuthenticatedAppDocumentsIdRouteWithChildren =
  AuthenticatedAppDocumentsIdRoute._addFileChildren(
    AuthenticatedAppDocumentsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppApprovalsRoute: typeof AuthenticatedAppApprovalsRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppChatbotRoute: typeof AuthenticatedAppChatbotRoute
  AuthenticatedAppDemoRoute: typeof AuthenticatedAppDemoRoute
  AuthenticatedAppPendingSignaturesRoute: typeof AuthenticatedAppPendingSignaturesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedSuperAdminAdminClientsRoute: typeof AuthenticatedSuperAdminAdminClientsRoute
  AuthenticatedSuperAdminTenantsRoute: typeof AuthenticatedSuperAdminTenantsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedAdminTemplatesIdRoute: typeof AuthenticatedAdminTemplatesIdRoute
  AuthenticatedAdminTemplatesNewRoute: typeof AuthenticatedAdminTemplatesNewRoute
  AuthenticatedAdminWorkflowsIdRoute: typeof AuthenticatedAdminWorkflowsIdRoute
  AuthenticatedAdminWorkflowsNewRoute: typeof AuthenticatedAdminWorkflowsNewRoute
  AuthenticatedAppDocumentsIdRoute: typeof AuthenticatedAppDocumentsIdRouteWithChildren
  AuthenticatedAppDocumentsNewRoute: typeof AuthenticatedAppDocumentsNewRoute
  AuthenticatedAppDocumentsWysiwygRoute: typeof AuthenticatedAppDocumentsWysiwygRoute
  AuthenticatedAdminBusinessVerticalsIndexRoute: typeof AuthenticatedAdminBusinessVerticalsIndexRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminWorkflowsIndexRoute: typeof AuthenticatedAdminWorkflowsIndexRoute
  AuthenticatedAppDocumentsIndexRoute: typeof AuthenticatedAppDocumentsIndexRoute
  AuthenticatedAppDraftsIndexRoute: typeof AuthenticatedAppDraftsIndexRoute
  AuthenticatedAppPdfTemplatesIndexRoute: typeof AuthenticatedAppPdfTemplatesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppApprovalsRoute: AuthenticatedAppApprovalsRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppChatbotRoute: AuthenticatedAppChatbotRoute,
  AuthenticatedAppDemoRoute: AuthenticatedAppDemoRoute,
  AuthenticatedAppPendingSignaturesRoute:
    AuthenticatedAppPendingSignaturesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedSuperAdminAdminClientsRoute:
    AuthenticatedSuperAdminAdminClientsRoute,
  AuthenticatedSuperAdminTenantsRoute: AuthenticatedSuperAdminTenantsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
  AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  AuthenticatedAdminTemplatesIdRoute: AuthenticatedAdminTemplatesIdRoute,
  AuthenticatedAdminTemplatesNewRoute: AuthenticatedAdminTemplatesNewRoute,
  AuthenticatedAdminWorkflowsIdRoute: AuthenticatedAdminWorkflowsIdRoute,
  AuthenticatedAdminWorkflowsNewRoute: AuthenticatedAdminWorkflowsNewRoute,
  AuthenticatedAppDocumentsIdRoute:
    AuthenticatedAppDocumentsIdRouteWithChildren,
  AuthenticatedAppDocumentsNewRoute: AuthenticatedAppDocumentsNewRoute,
  AuthenticatedAppDocumentsWysiwygRoute: AuthenticatedAppDocumentsWysiwygRoute,
  AuthenticatedAdminBusinessVerticalsIndexRoute:
    AuthenticatedAdminBusinessVerticalsIndexRoute,
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminWorkflowsIndexRoute: AuthenticatedAdminWorkflowsIndexRoute,
  AuthenticatedAppDocumentsIndexRoute: AuthenticatedAppDocumentsIndexRoute,
  AuthenticatedAppDraftsIndexRoute: AuthenticatedAppDraftsIndexRoute,
  AuthenticatedAppPdfTemplatesIndexRoute:
    AuthenticatedAppPdfTemplatesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  GuestTokenRoute: GuestTokenRoute,
  GuestNewRoute: GuestNewRoute,
  PTokenRoute: PTokenRoute,
  PayCancelledRoute: PayCancelledRoute,
  PaySuccessRoute: PaySuccessRoute,
  STokenRoute: STokenRoute,
  GuestIndexRoute: GuestIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicShareTokenRoute: ApiPublicShareTokenRoute,
  ApiPublicSignRequestTokenRoute: ApiPublicSignRequestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
