/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated.super-admin.index'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated.reseller.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedSuperAdminTenantsRouteImport } from './routes/_authenticated.super-admin.tenants'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppApprovalsRouteImport } from './routes/_authenticated.app.approvals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAppDocumentsIndexRouteImport } from './routes/_authenticated.app.documents.index'
import { Route as AuthenticatedAdminWorkflowsIndexRouteImport } from './routes/_authenticated.admin.workflows.index'
import { Route as AuthenticatedAppDocumentsNewRouteImport } from './routes/_authenticated.app.documents.new'
import { Route as AuthenticatedAppDocumentsIdRouteImport } from './routes/_authenticated.app.documents.$id'
import { Route as AuthenticatedAdminWorkflowsNewRouteImport } from './routes/_authenticated.admin.workflows.new'
import { Route as AuthenticatedAdminWorkflowsIdRouteImport } from './routes/_authenticated.admin.workflows.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/super-admin/',
    path: '/super-admin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/reseller/',
    path: '/reseller/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminTenantsRoute =
  AuthenticatedSuperAdminTenantsRouteImport.update({
    id: '/super-admin/tenants',
    path: '/super-admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppApprovalsRoute =
  AuthenticatedAppApprovalsRouteImport.update({
    id: '/app/approvals',
    path: '/app/approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppDocumentsIndexRoute =
  AuthenticatedAppDocumentsIndexRouteImport.update({
    id: '/app/documents/',
    path: '/app/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsIndexRoute =
  AuthenticatedAdminWorkflowsIndexRouteImport.update({
    id: '/admin/workflows/',
    path: '/admin/workflows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsNewRoute =
  AuthenticatedAppDocumentsNewRouteImport.update({
    id: '/app/documents/new',
    path: '/app/documents/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppDocumentsIdRoute =
  AuthenticatedAppDocumentsIdRouteImport.update({
    id: '/app/documents/$id',
    path: '/app/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsNewRoute =
  AuthenticatedAdminWorkflowsNewRouteImport.update({
    id: '/admin/workflows/new',
    path: '/admin/workflows/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsIdRoute =
  AuthenticatedAdminWorkflowsIdRouteImport.update({
    id: '/admin/workflows/$id',
    path: '/admin/workflows/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/admin/workflows/': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/app/documents': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/approvals': typeof AuthenticatedAppApprovalsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/admin/workflows/$id': typeof AuthenticatedAdminWorkflowsIdRoute
  '/_authenticated/admin/workflows/new': typeof AuthenticatedAdminWorkflowsNewRoute
  '/_authenticated/app/documents/$id': typeof AuthenticatedAppDocumentsIdRoute
  '/_authenticated/app/documents/new': typeof AuthenticatedAppDocumentsNewRoute
  '/_authenticated/admin/workflows/': typeof AuthenticatedAdminWorkflowsIndexRoute
  '/_authenticated/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/app/approvals'
    | '/app/profile'
    | '/super-admin/tenants'
    | '/admin/'
    | '/app/'
    | '/reseller/'
    | '/super-admin/'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/app/documents/$id'
    | '/app/documents/new'
    | '/admin/workflows/'
    | '/app/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/app/approvals'
    | '/app/profile'
    | '/super-admin/tenants'
    | '/admin'
    | '/app'
    | '/reseller'
    | '/super-admin'
    | '/admin/workflows/$id'
    | '/admin/workflows/new'
    | '/app/documents/$id'
    | '/app/documents/new'
    | '/admin/workflows'
    | '/app/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/approvals'
    | '/_authenticated/app/profile'
    | '/_authenticated/super-admin/tenants'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/reseller/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/admin/workflows/$id'
    | '/_authenticated/admin/workflows/new'
    | '/_authenticated/app/documents/$id'
    | '/_authenticated/app/documents/new'
    | '/_authenticated/admin/workflows/'
    | '/_authenticated/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/reseller'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/tenants': {
      id: '/_authenticated/super-admin/tenants'
      path: '/super-admin/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof AuthenticatedSuperAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/approvals': {
      id: '/_authenticated/app/approvals'
      path: '/app/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AuthenticatedAppApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/': {
      id: '/_authenticated/app/documents/'
      path: '/app/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/': {
      id: '/_authenticated/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows/'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/new': {
      id: '/_authenticated/app/documents/new'
      path: '/app/documents/new'
      fullPath: '/app/documents/new'
      preLoaderRoute: typeof AuthenticatedAppDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/documents/$id': {
      id: '/_authenticated/app/documents/$id'
      path: '/app/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/new': {
      id: '/_authenticated/admin/workflows/new'
      path: '/admin/workflows/new'
      fullPath: '/admin/workflows/new'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows/$id': {
      id: '/_authenticated/admin/workflows/$id'
      path: '/admin/workflows/$id'
      fullPath: '/admin/workflows/$id'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAppApprovalsRoute: typeof AuthenticatedAppApprovalsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedSuperAdminTenantsRoute: typeof AuthenticatedSuperAdminTenantsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedAdminWorkflowsIdRoute: typeof AuthenticatedAdminWorkflowsIdRoute
  AuthenticatedAdminWorkflowsNewRoute: typeof AuthenticatedAdminWorkflowsNewRoute
  AuthenticatedAppDocumentsIdRoute: typeof AuthenticatedAppDocumentsIdRoute
  AuthenticatedAppDocumentsNewRoute: typeof AuthenticatedAppDocumentsNewRoute
  AuthenticatedAdminWorkflowsIndexRoute: typeof AuthenticatedAdminWorkflowsIndexRoute
  AuthenticatedAppDocumentsIndexRoute: typeof AuthenticatedAppDocumentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAppApprovalsRoute: AuthenticatedAppApprovalsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedSuperAdminTenantsRoute: AuthenticatedSuperAdminTenantsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
  AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  AuthenticatedAdminWorkflowsIdRoute: AuthenticatedAdminWorkflowsIdRoute,
  AuthenticatedAdminWorkflowsNewRoute: AuthenticatedAdminWorkflowsNewRoute,
  AuthenticatedAppDocumentsIdRoute: AuthenticatedAppDocumentsIdRoute,
  AuthenticatedAppDocumentsNewRoute: AuthenticatedAppDocumentsNewRoute,
  AuthenticatedAdminWorkflowsIndexRoute: AuthenticatedAdminWorkflowsIndexRoute,
  AuthenticatedAppDocumentsIndexRoute: AuthenticatedAppDocumentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
